name: Docker Image CI

on:
  workflow_dispatch:  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3        
    - name: Docker Login
      run: echo ${{secrets.DOCKER_PASSWORD}} | docker login --password-stdin -u ${{secrets.DOCKER_USER}}
    
    - name: Build Docker Images
      run: |        
        docker build -t dhcr:latest -t vimalgupta/dhcr:app-${{secrets.github.sha}} . -f Inventory.API/Dockerfile
    - name: Publish Docker Images
      run: docker push vimalgupta/dhcr:app-${{secrets.github.sha}}
  
    - name: Azure login
      id: login
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Set AKS context
      id: set-context
      uses: azure/aks-set-context@v3
      with:
        resource-group: '${{ secrets.resource_group }}' 
        cluster-name: '${{ secrets.cluster_name }}'
    - name: Setup kubectl
      id: install-kubectl
      uses: azure/setup-kubectl@v3
    - name: Set imagePullSecret
      uses: azure/k8s-create-secret@v4
      with:
        namespace: 'default'
        secret-name: 'docker-secret'
        container-registry-url: 'docker.io'
        container-registry-username: ${{ secrets.DOCKER_USER }}
        container-registry-password: ${{ secrets.DOCKER_PASSWORD }}
      id: create-secret
    - name: Deploy to AKS
      id: deploy-aks
      uses: Azure/k8s-deploy@v4
      with:
        namespace: 'default'
        manifests: |
            inventory-deploy.yaml
        images: |
            vimalgupta/dhcr/app-${{secrets.github.sha}}    
        imagepullsecrets: |
            docker-secret 